/*
 * This source file was generated by the Gradle 'init' task
 */
package cse311;

import cse311.Constants.MemoryMode;
import cse311.Constants.OSConstants;
import cse311.Logger.FileLogger;
import cse311.kernel.Kernel;
import cse311.kernel.KernelConfig;
import cse311.programs.InitTask;
import java.io.File;

@SuppressWarnings({"PMD.AvoidCatchingGenericException", "PMD.AvoidCatchingNPE"})
public class App {

    public static void main(String[] args) {
        FileLogger.log("==========================================");
        FileLogger.log("      RISC-V Java Kernel Bootloader       ");
        FileLogger.log("==========================================");

        try {
            // --------------------------------------------------------
            // 1. HARDWARE INIT
            // --------------------------------------------------------
            // Initialize 128MB RAM, CPU, Memory Management Techniques
            RV32Computer computer = new RV32Computer(1024 * 1024 * 12, Integer.MAX_VALUE, MemoryMode.PAGING);
            Kernel kernel = computer.getKernel();

            // --------------------------------------------------------
            // 2. KERNEL CONFIGURATION
            // --------------------------------------------------------
            // Use Round Robin to allow Init, Shell, and User apps to share CPU
            kernel.getConfig().setSchedulerType(KernelConfig.SchedulerType.ROUND_ROBIN);
            // Set Time Slice to X instructions (Thread-safe delegate call)
            kernel.setTimeSlice(3);

            // --------------------------------------------------------
            // 3. MOUNT FILE SYSTEM
            // --------------------------------------------------------
            String imgPath = ".." + OSConstants.file_seperator + "fs.img";
            File diskImage = new File(imgPath);
            if (diskImage.exists()) {
                kernel.mountFileSystem(imgPath);
                FileLogger.log("Disk image 'fs.img' loaded.");
            } else {
                FileLogger.log("Warning: 'fs.img' not found. File system calls will fail.");
                FileLogger.log("Run 'cse311.Mkfs' to generate the disk image.");
            }

            // --------------------------------------------------------
            // 4. LAUNCH INIT PROCESS (PID 1)
            // Java Simulated Init Task or from ELF
            // --------------------------------------------------------
            FileLogger.log("Bootloader: Spawning Init process (PID 1)...");

            // Load Init from ELF
            String elfPath = "app" + OSConstants.file_seperator + "src" + OSConstants.file_seperator + "main"
                    + OSConstants.file_seperator +
                    "resources" + OSConstants.file_seperator + "user_programs" + OSConstants.file_seperator
                    + "init.elf";
            FileLogger.log("Current working directory: " + System.getProperty("user.dir"));
            FileLogger.log("Looking for ELF at: " + elfPath);
            File f = new File(elfPath);
            FileLogger.log("File exists: " + f.exists());
            FileLogger.log("Absolute path: " + f.getAbsolutePath());
            if (f.exists()) {
                FileLogger.log("Bootloader: Pre-loading user ELF: " + elfPath);
                kernel.createTask(elfPath);
            } else {
                // Fallback to old path for backwards compatibility
                String oldPath = ".." + OSConstants.file_seperator + "User_Program_ELF" + OSConstants.file_seperator
                        + "init.elf";
                File oldFile = new File(oldPath);
                if (oldFile.exists()) {
                    FileLogger.log("Bootloader: Using legacy ELF path: " + oldPath);
                    kernel.createTask(oldPath);
                }
            }

            // --------------------------------------------------------
            // 5. START KERNEL
            // --------------------------------------------------------

        } catch (NullPointerException e) {
            FileLogger.log("Path invalid: " + e.getMessage());
            FileLogger.log(e);
        } catch (Exception e) {
            FileLogger.log("\nKERNEL PANIC: " + e.getMessage());
            FileLogger.log(e);
        } finally {
            FileLogger.log("\nSystem Halted.");
        }
    }
}